# This file was generated by GoReleaser. DO NOT EDIT.
cask "es" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "af6c115779ab272bdb6c1d06869002b7b510e8023b1d6fb2d5517332fe3159c3"
      url "https://github.com/everscribe/cli/releases/download/v#{version}/es_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c5bb757291e5cbc9605726d0cfe768fbdf5845214aaa97b5da24a4096912b8e"
      url "https://github.com/everscribe/cli/releases/download/v#{version}/es_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4f1bf714174bfac6927925d7ec141fa30bfa1d6018c7dd4f0fa671bf9e4420a7"
      url "https://github.com/everscribe/cli/releases/download/v#{version}/es_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "37582de7db4d3c7f1e06c3258abe43c68a6328077e5640756348ac5a2e9c0fe7"
      url "https://github.com/everscribe/cli/releases/download/v#{version}/es_#{version}_linux_amd64.tar.gz"
    end
  end

  name "es"
  desc "Command-line interface for Everscribe"
  homepage "https://everscribe.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "es"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/es"]
    end
  end

  # No zap stanza required
end
